#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'miniMaxSum' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def miniMaxSum(arr):
    summs = []
    init = 0
    while init < len(arr):
        sum_el = sum(arr) - arr[init]
        summs.append(sum_el)
        init += 1
    print(min(summs), max(summs))
    
if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
