#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    n = len(arr)
    cnt = arr.count(0)
    if cnt == 0:
        arr.append(0)
    idx = sorted(arr).index(0)
    neg = idx/n
    zeros = cnt/n
    pos = 1 - neg - zeros
    print(pos)
    print(neg)
    print(zeros)
    
if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
